### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#102]
We are now set to go on the development of the website. I am going to split this into components and custom layouts. @mxstbr feel free to edit any issues and breaking them down if needed.

## Header

The mashead is fairly simple and straight forward, only thing that needs to be replaced is Slack for Gitter. We are also missing the masthead hero image #105 and the new updated [logotype font](https://github.com/postcss/brand/issues/13)

You can find all the necessary styleguide info from Zeplin - #98

**Comment by marcustisater** [comment]
![screenshot-header](https://cloud.githubusercontent.com/assets/2952332/12494002/348d29da-c088-11e5-9ab5-c40310bd56b2.png)

**Comment by mxstbr** [comment]
Nice, finally! 👌🏼 Thanks for splitting these up, will start dev soon!

**Comment by marcustisater** [comment]
Sounds good. I will try to break it down to as many issues as possible.

Yes, finally! :smile:

**Comment by jeddy3** [comment]
I've made a start on this...

**Comment by marcustisater** [comment]
Great work but we are missing one thing - the github integration.

**Comment by jeddy3** [comment]
It's an easy add:

```html
<iframe src="https://ghbtns.com/github-btn.html?user=twbs&repo=bootstrap&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
```

To `Hero`.

However, I wasn't too sure about this. I did add it at one point, but then stripped it out again because I found it interfered with the natural flow through the page. Right now we have the Hero that introduces PostCSS with its logo and tagline. This then leads into the examples of some tools built with PostCSS. Adding a star button breaks that follow by sticking an external link smack in the middle of the introduction and the examples. It's a disorientating jump.

Also, and I'm not sure what your thoughts are on this, I think PostCSS now has enough traction so that showing its popularity (via the number of stars) doesn't need to be emphasised so much.

So, given the break in flow and diminishing need to show popularity, I'd suggest not adding it. I'm easy either way though and there might be some other reasons for it that I'm not aware of :)

**Comment by marcustisater** [comment]
Ah yeah, you are right. `iframe` is enough for this. 

@okonet - any thoughts regarding this?

**Comment by okonet** [comment]
These are good points indeed. Let's try without the button. We can always change later.

**Comment by jeddy3** [comment]
> Let's try without the button.

:+1:  :)

**Comment by jeddy3** [comment]
Oops, pretty presumptuous of me to close the issue. I'll leave that to you @marcustisater  :)

**Comment by marcustisater** [comment]
No, i'ts fine. I think we can close this one out.

Great job and thanks for quick input @okonet
