### ISSUE TITLE
Global CSS overriding everything

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.org#115]
We have some global CSS in the `Wrapper` component `index.css` file for some general styling from the Statinamic boilerplate. The problem is that those styles override everything else (e.g. an `a` tag won't ever have a different color) because they come after the other styles in the DOM.

How do we fix that @MoOx?

**Comment by MoOx** [comment]
Use less global CSS, use more classes (css modules).
Combine both if needed (`.local tag` => more specificity for 'tag').
Does that help?

**Comment by mxstbr** [comment]
Not really sadly, because the global CSS is stuff like headings and such. That should be at the top and be overridden by everything else, not the other way around...

**Comment by ai** [comment]
We decided to avoid global CSS, so we should avoid it here too.

**Comment by marcustisater** [comment]
I thought the point of doing CSS Modules is not to do anything by global styles?

**Comment by mxstbr** [comment]
Me too, but the styles were already in there. I'll remove them then!

**Comment by MoOx** [comment]
@marcustisater currently the default boilerplate (because I was lazy) use some `:global` selector (which, when you are in "css modules" mode, allow you to use "non modules" selectors (when you are lazy or have to work with something where you cannot control class names).

You can easily avoid that by using a component for everything (eg a component for heading, one for Link etc), and this should be done this way imo.

@mxstbr for things that must be global (like reset/normalize/high level defaults), you can probably import a css before the statinamic client function.

Anyway, not a big deal to adjust the shot (that said, I heard you and will this better in statinamic by default) https://github.com/MoOx/statinamic/issues/95

**Comment by mxstbr** [comment]
:+1: will do, thanks @MoOx!

**Comment by marcustisater** [comment]
Ahaa, I see. Thank you for the explanation @MoOx

**Comment by mxstbr** [comment]
#125
