### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#211]
GitHub pages supports SSL. Could we use it for custom domain?

https://github.com/blog/2186-https-for-github-pages

**Comment by marcustisater** [comment]
That's cool. Unfortunately it does not work on custom domains. 

> "HTTPS is not supported for GitHub Pages using custom domains."

Read more: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by thangngoc89** [comment]
You guys can use Cloudflare or [Kloudsec](https://kloudsec.com/github-pages/new) for HTTPS.

**Comment by marcustisater** [comment]
Ah, I didn't know that. 

@ai thoughts?

**Comment by ai** [comment]
@thangngoc89 Kloudsec looks promising. What do we need? How it works? What is the price?

**Comment by thangngoc89** [comment]
@ai It's currently free. All you need is point your domain to kloudsec. (Just follow the instruction on the page)

**Comment by marcustisater** [comment]
I can set it up if you would like. I have domain info.

**Comment by ai** [comment]
@marcustisater awesome, let’s try! Ping me when you will finish it.

**Comment by marcustisater** [comment]
will do

**Comment by marcustisater** [comment]
Sorry... 😓 

https://kloudsec.com/ is offline. Any other tips for https?

**Comment by thangngoc89** [comment]
https://www.netlify.com 
Is a full service for static page

**Comment by okonet** [comment]
Netlify is cool. I second this.

**Comment by marcustisater** [comment]
Agree, it works great https://public-relations-officer-claudia-65056.netlify.com/. I just need to change DNS.

**Comment by marcustisater** [comment]
> Ah, you use gandi.net (so do I - but not for DNS because of what I'm about to say).  They don't support an ALIAS or ANAME or flattened CNAME record which is the best way to get full advantage of our CDN for your bare domain (vs www.postcss.org which should be the CNAME you mention).
Two suggestions, one related and one unrelated:
if you don't mind, using 'www.postcss.org' instead of 'postcss.org' for your canonical hostname - put it as the custom domain in your settings page instead of 'postcss.org' - this will work around this and your visitors will get to use the CDN (we'll 301 redirect from postcss.org -> www.postcss.org automatically so all the content will come from the CDN even though the redirect comes from our one-location load balancer)
you should upgrade yourself to the open source plan here: https://app.netlify.com/sites/public-relations-officer-claudia-65056/plan . Your site definitely is the type of site we're intending to help out with our free open source plan!
I understand if for #1 you really prefer to use 'postcss.org' instead of 'www.postcss.org' but in that case I'd recommend getting a more capable DNS provider like CloudFlare (also I think should be free for your use case) - they support CNAME flattening so you can CNAME your apex domain and still process mail and do all the normal things with that domain.

I talked to @ai and we have decided to wait with this.

**Comment by sidoruk-sv** [comment]
@marcustisater thanks for that message! Also configured DNS in gandi.net and trying to find some information about their support for `ALIAS` or `ANAME` records. So your message is very helpful.

Also, as @ai [posted](https://twitter.com/sitnikcode/status/991771268474134529) about easing.net and HTTPS support for custom domains thought that this thread should be restored.

**Comment by ai** [comment]
@marcustisater yeap, I can confirm, HTTPS works great on GitHub Pages for custom domains.

Here is an instruction:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Can I ask you to enable it since I am preparing 2 talks in the same time :(

**Comment by marcustisater** [comment]
We are now running on https 🎉

**Comment by ai** [comment]
@marcustisater 🎉 Thanks!

I changed links from `postcss/postcss`

Will make a Twitter announce on next week
